# This workflow checks Terraform formatting on every pull request that modifies .tf files
# It helps enforce consistent code style and prevents unformatted code from being merged

name: Terraform Format Check

on:
  # Trigger the workflow on pull requests that change any .tf file
  pull_request:
    paths:
      - '**.tf'

jobs:
  terraform-fmt:
    # Use the latest Ubuntu runner for the job
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository code so the workflow can access it
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Terraform CLI using the official HashiCorp action
      # You can specify the required Terraform version here
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      # Step 3: Run 'terraform fmt -check -recursive' to check formatting
      # -check: Fails if any file is not properly formatted
      # -recursive: Checks all .tf files in all subdirectories
      - name: Check Terraform formatting
        run: terraform fmt -check -recursive 
